experiment:
  name: GHOST_no_coro

algorithms:
  CADI: true
  PCAD: true

datasets:
  int:
    enabled: true
    science_file: /home/aosimul/noah/data/ghost_images/4ms/stg2_int.npy

  pred:
    enabled: true
    science_file: /home/aosimul/noah/data/ghost_images/4ms/stg2_pred.npy

instrument:
  frame_rate: 0.0025
  dit_science: 0.004
  dit_psf: 10
  pixel_size: 0.005
  radius_psf: 20

fake_planet:
  flux_ratio_mag: 16
  num_fake_planets: 3
  components: [5, 10]

  separation: 2
  max_separation: 0.5

  approx_svd_trunc: null
  device: "cuda"

  angle_start: 0
  angle_end: 30